import pandas as pd
import sys

def print_simulation_table(file_path: str, scenario_name: str, top_n: int = 5):
    """
    Reads detailed Monte Carlo simulation results and prints a formatted
    table for reporting purposes.
    """
    try:
        # Read the CSV generated by the Hybrid_pricing_engine
        df = pd.read_csv(file_path, sep=';')
        
        # Filter for the specific scenario
        scenario_data = df[df['Scenario'] == scenario_name].head(top_n)

        if scenario_data.empty:
            print(f"Warning: No data found for scenario '{scenario_name}'.")
            return

        # Print header
        print(f"\n Table 3 (Scenario: {scenario_name})")
        print("-" * 80)
        print(f"{'Sim ID':<8} | {'Random Z':<12} | {'Spot (S_T)':<12} | {'Payoff (PV)':<12} | {'Hybrid Val':<12}")
        print("-" * 80)

        # Print rows
        for _, row in scenario_data.iterrows():
            print(f"{int(row['Sim_ID']):<8} | "
                  f"{row['Random_Z']:<12.4f} | "
                  f"{row['Simulated_Spot']:<12.2f} | "
                  f"{row['MC_Payoff_PV']:<12.4f} | "
                  f"{row['Hybrid_Value']:.4f}")
        
        print("-" * 80)
        print(f"Showing top {top_n} rows for report extraction.\n")

    except FileNotFoundError:
        print(f"Error: Could not find '{file_path}'.")
        print("Please run 'hybrid_pricing_engine.py' first to generate the data.")
        sys.exit(1)

if __name__ == "__main__":
    # Test the formatter using the English scenario name we defined in the engine
    print_simulation_table('simulation_details.csv', 'PKO_BP_Shock', top_n=5)